const baseUrl = "https://app-a47db9eb-20ff-46a5-b338-2d54b7f96516.cleverapps.io";
//const baseUrl = "http://localhost:2525";
export const USER_LOGIN = `${baseUrl}/login`;
export const USER_REGISTER = `${baseUrl}/registerUser`;
export const GET_TRACKERS_BY_USER_ID = `${baseUrl}/getTrackersByUserId`;
export const ADD_TRANSACTION = `${baseUrl}/addTransaction`;
export const ADD_TRACKER = `${baseUrl}/addTracker`;
export const UPDATE_TRANSACTION = `${baseUrl}/updateTransaction`;
export const ADD_MEMBER = `${baseUrl}/addMember`;